/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufmt.ic.posbd.escolar.gui;

import br.ufmt.ic.posbd.escolar.FabricaDAO;
import br.ufmt.ic.posbd.escolar.dao.CursoDisciplinaDAO;
import br.ufmt.ic.posbd.escolar.tableModel.CursoDisciplinaTableModel;
import br.ufmt.ic.posbd.escolarPostgresql.entidade.Curso;
import br.ufmt.ic.posbd.escolarPostgresql.entidade.CursoDisciplina;
import br.ufmt.ic.posbd.escolarPostgresql.entidade.Disciplina;
import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author raphael
 */
public class CursoDisciplinaJPanel extends javax.swing.JPanel {

    private CursoDisciplinaTableModel tableModel;
    private CursoDisciplinaDAO dao = FabricaDAO.criarCursoDisciplinaDAO();

    /**
     * Creates new form CursoDisciplinaJPanel
     */
    public CursoDisciplinaJPanel() {
        tableModel = new CursoDisciplinaTableModel(dao.listar());
        initComponents();
        cursojComboBox.removeAllItems();
        cursojComboBox.addItem("Selecione");
        List<Curso> cursos = FabricaDAO.criarCursoDAO().listar();
        for (Curso curso : cursos) {
            cursojComboBox.addItem(curso);
        }
        disciplinajComboBox.removeAllItems();
        disciplinajComboBox.addItem("Selecione");
        List<Disciplina> disciplinas = FabricaDAO.criarDisciplinaDAO().listar();

        for (Disciplina disciplina : disciplinas) {
            disciplinajComboBox.addItem(disciplina);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelajTable = new javax.swing.JTable();
        excluirjButton = new javax.swing.JButton();
        cursojLabel = new javax.swing.JLabel();
        cursojComboBox = new javax.swing.JComboBox();
        disciplinajLabel = new javax.swing.JLabel();
        disciplinajComboBox = new javax.swing.JComboBox();
        salvarjButton = new javax.swing.JButton();

        tabelajTable.setModel(tableModel);
        jScrollPane1.setViewportView(tabelajTable);

        excluirjButton.setText("Excluir");
        excluirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirjButtonActionPerformed(evt);
            }
        });

        cursojLabel.setText("Curso:");

        cursojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        disciplinajLabel.setText("Disciplina:");

        disciplinajComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        salvarjButton.setText("Adicionar");
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(excluirjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(disciplinajLabel)
                            .addComponent(cursojLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(salvarjButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cursojComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(disciplinajComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursojLabel)
                    .addComponent(cursojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disciplinajLabel)
                    .addComponent(disciplinajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvarjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(excluirjButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void excluirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirjButtonActionPerformed
        // TODO add your handling code here:
        int[] linhas = tabelajTable.getSelectedRows();
        if (JOptionPane.showConfirmDialog(excluirjButton, "Deseja realmente excluir?") == JOptionPane.YES_OPTION) {
            for (int i = 0; i < linhas.length; i++) {
                CursoDisciplina cursoDisciplina = tableModel.get(linhas[i]);
                dao.excluir(cursoDisciplina.getId());
            }
            JOptionPane.showMessageDialog(tabelajTable, "Removidos com Sucesso!");
            tableModel.atualizar(dao.listar());
        }
    }//GEN-LAST:event_excluirjButtonActionPerformed

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:
        if (cursojComboBox.getSelectedIndex() > 0) {
            CursoDisciplina cursoDisciplina = new CursoDisciplina();

            cursoDisciplina.setCurso((Curso) cursojComboBox.getSelectedItem());
            cursoDisciplina.setDisciplina((Disciplina) disciplinajComboBox.getSelectedItem());

            if (dao.exists(cursoDisciplina.getCurso(), cursoDisciplina.getDisciplina())) {
                JOptionPane.showMessageDialog(salvarjButton, "Já existe disciplina neste curso!");
            } else {
                dao.inserir(cursoDisciplina);
                JOptionPane.showMessageDialog(salvarjButton, "Inserido com Sucesso!");
                tableModel.atualizar(dao.listar());
                cursojComboBox.setSelectedIndex(0);
                disciplinajComboBox.setSelectedIndex(0);
            }
        } else {
            JOptionPane.showMessageDialog(cursojComboBox, "Selecione o curso");
            cursojComboBox.grabFocus();
        }
    }//GEN-LAST:event_salvarjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cursojComboBox;
    private javax.swing.JLabel cursojLabel;
    private javax.swing.JComboBox disciplinajComboBox;
    private javax.swing.JLabel disciplinajLabel;
    private javax.swing.JButton excluirjButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JTable tabelajTable;
    // End of variables declaration//GEN-END:variables
}
