/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.ufmt.ic.posbd.escolar.gui;

import javax.swing.JPanel;

/**
 *
 * @author raphael
 */
public class PrincipalJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalJFrame
     */
    public PrincipalJFrame() {
        initComponents();
    }

    private void setConteudo(JPanel tela){
        conteudojPanel.removeAll();
        conteudojPanel.add(tela);
        conteudojPanel.setVisible(false);
        conteudojPanel.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conteudojPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        salajMenuItem = new javax.swing.JMenuItem();
        modalidadejMenuItem = new javax.swing.JMenuItem();
        cursojMenuItem = new javax.swing.JMenuItem();
        disciplinajMenuItem = new javax.swing.JMenuItem();
        cursoDisciplinajMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        conteudojPanel.setLayout(new javax.swing.BoxLayout(conteudojPanel, javax.swing.BoxLayout.LINE_AXIS));

        jMenu1.setText("File");

        salajMenuItem.setText("Sala");
        salajMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salajMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(salajMenuItem);

        modalidadejMenuItem.setText("Modalidade");
        modalidadejMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modalidadejMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(modalidadejMenuItem);

        cursojMenuItem.setText("Curso");
        cursojMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursojMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(cursojMenuItem);

        disciplinajMenuItem.setText("Disciplina");
        disciplinajMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disciplinajMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(disciplinajMenuItem);

        cursoDisciplinajMenuItem.setText("Disciplinas do Curso");
        cursoDisciplinajMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursoDisciplinajMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(cursoDisciplinajMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conteudojPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conteudojPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salajMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salajMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new SalaJPanel());
    }//GEN-LAST:event_salajMenuItemActionPerformed

    private void modalidadejMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modalidadejMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new ModalidadeJPanel());
    }//GEN-LAST:event_modalidadejMenuItemActionPerformed

    private void cursojMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursojMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new CursoJPanel());
    }//GEN-LAST:event_cursojMenuItemActionPerformed

    private void disciplinajMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disciplinajMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new DisciplinaJPanel());
    }//GEN-LAST:event_disciplinajMenuItemActionPerformed

    private void cursoDisciplinajMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoDisciplinajMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new CursoDisciplinaJPanel());
    }//GEN-LAST:event_cursoDisciplinajMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel conteudojPanel;
    private javax.swing.JMenuItem cursoDisciplinajMenuItem;
    private javax.swing.JMenuItem cursojMenuItem;
    private javax.swing.JMenuItem disciplinajMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem modalidadejMenuItem;
    private javax.swing.JMenuItem salajMenuItem;
    // End of variables declaration//GEN-END:variables
}
